### ISSUE TITLE
Doesn't work if 'quickfixtextfunc' is set

### ISSUE THREAD

**Issue by backdround** [itchyny/vim-qfedit#11]
When I have the option `'quickfixtextfunc'` set and try to delete a line the quickfix buffer clears entirely.

**Comment by itchyny** [comment]
How can we detect that the current quickfix or location fix window is opened with the `'quickfixtextfunc'` option enabled? Although it is a global option, it can also be set by the option of `setqflist()` and `setloclist()`, so I cannot find a reliable way of knowing how the quickfix item texts are constructed. What do you suggest?

**Comment by backdround** [comment]
I'm not sure why we need this, but the only way I see to know that the quickfix / location list is opened with the effect of `quickfixtextfunc` is to save the variable state for an opened buffer every `BufWinEnter`. And when we need to detect whether the current buffer was opened with the set option, we will ask our dictionary

**Comment by itchyny** [comment]
I don't think we can peek the option state even if at `BufWinEnter` event. This plugin is implemented by matching the buffer lines against the quickfix items, reconstructing the items back from the buffer, and reset using `setqflist()`.

**Comment by itchyny** [comment]
I don't think I can fix this issue. Closing as wontfix.
