### ISSUE TITLE
When opening the QuickFix window automatically, initialization fails

### ISSUE THREAD

**Issue by tsuyoshicho** [itchyny/vim-qfedit#3]
Problem:

vim-qfedit with "quickfix auto open" together, it dose not work.

Reproduction:

Start vim

```
gvim -u -N .vimrc
```

and exec 2 ex command

```
:autocmd BufReadPost quickfix echom 'call autocmd'
:autocmd QuickFixCmdPost vimgrep cwindow
```

when start `:vim` (ex `vim set %` ), and then `message` check.

Result:
Do not echo 'call autocmd'

Workaround:
When occur it, qf open/close toggled, then vim-qfedit work fine.

I hope fix it.
Suggestion, use `autocmd Filetype qf` are solved it?

**Comment by itchyny** [comment]
Please specify nested attribute.
```vim
autocmd QuickFixCmdPost vimgrep nested cwindow
```

**Comment by tsuyoshicho** [comment]
That's no surprise, thanks sure.
