### ISSUE TITLE
quickfix still not modifiable ?

### ISSUE THREAD

**Issue by mckellyln** [itchyny/vim-qfedit#4]
Hi,
I saw this plugin and am happy to try it out.
Thank you for awesome lightline.
So I installed this via Vundle, but my quickfix window is still not modifiable.
If I manually go to qf win and then :set ma all is ok, but I wanted to find a way to make it modifiiable always.
Any idea how I can help debug ?
I tried removing a few other plugins related to qf, but I still have the same problem.
thx for any help or suggestion,
-m

**Comment by itchyny** [comment]
This might be the nested event problem, if you use `QuickfixCmdPost` event, add ++nested attribute.

**Comment by mckellyln** [comment]
Hi,
I don't use QuickfixCmdPost, but a few other plugins I have do.  I'll go through them and see.
I have a work-around also for now, so we can close this issue.  If I find something I'll post it.
thx,
-m

**Comment by itchyny** [comment]
`:verbose set modified?` might help.
