### ISSUE TITLE
If "zero bytes" specified for setloclist, not work.

### ISSUE THREAD

**Issue by rapan931** [itchyny/vim-qfedit#8]
Thanks for the great plugin.

## reproduced

1. gvim.exe -Nu miminal.vimrc
``` vim
" minimal.vimrc

" add vim-qfedit to runtimepath
set packpath=$HOME/pack_minimal
packadd vim-qfedit
```
2. Iaaa\<C-v>0bbb\<C-v>0ccc\<ESC>
3. 0yg_  " copy the string containing zero bytes.
4. :call setloclist(0, [{'lnum': 1, 'col': 1, 'filename': 'C:\r.rb', 'type': 'E', 'text': getreg(v:register)}]) \<CR>" set zero bytes to locallist
5. :lopen\<CR>
6. \<C-w>k
7. :call setloclist(0, [{'lnum': 1, 'col': 1, 'filename': 'C:\r.rb', 'type': 'E', 'text': getreg(v:register)}])\<CR>
8. :lopen\<CR>

## expected
The string should be displayed at location list.

## actual
Nothing is displayed.

## my env
windows 10

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 16 2021 22:02:45)
MS-Windows 64 ビット GUI 版 with OLE サポート
適用済パッチ: 1-3356
Compiled by appveyor@APPVYR-WIN

## others
I noticed this behavior when using vim-lsp, vim-lsp-setting and vim-qfedit

0. (echo excecutable('solargraph') " => 1)
1. gvim.exe -Nu minimal2.vimrc run.rb
``` vim
" minimal2.vimrc

" add vim-lsp, vim-lsp-setting and vim-qfedit to runtimepath
set packpath=$HOME/pack_minimal
packadd vim-lsp-settings
packadd vim-lsp
packadd vim-qfedit

filetype plugin indent on
syntax enable
```
3. :e c:\path\to\err.rb\<CR>
``` ruby
" err.rb
r = r + hoge "11"
```

4. :LspDocumentDiagnostics\<CR>
5. :LspDocumentDiagnostics\<CR>
  -> Nothing is displayed.

This behavior may be caused by the following that vim-lsp sets the location list to a string containing zero bytes, but vim-qfedit compares with a string in which zero bytes are excluded.

**Comment by itchyny** [comment]
Thanks for reporting, Fixed.
